micronaut:
  application:
    name: money-transfer-mn
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:h2:mem:accountDB;DB_CLOSE_DELAY=-1;INIT=runscript from 'classpath:init.sql'
    username: moneytransfer
    password: ""
    driverClassName: org.h2.Driver


